"""تبدیل کوکی‌های Playwright به فایل Netscape برای yt-dlp."""

from __future__ import annotations

import time
from pathlib import Path
from typing import Iterable


def export_netscape_cookies(cookies: Iterable[dict], path: Path | str) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by Insta Reels Agent — مخصوص yt-dlp",
        "",
    ]
    now = int(time.time())
    for c in cookies:
        domain = c.get("domain", "") or ""
        if not domain or domain.startswith("__"):
            pass  # __Host-/__Secure- prefix‌ها را خود yt-dlp تشخیص می‌دهد
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        cpath = c.get("path", "/") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires") or 0)
        if expires < 0:
            expires = now + 3600  # کوکی نشست: یک ساعت اعتبار فرضی
        name = str(c.get("name", ""))
        value = str(c.get("value", "")).replace("\t", " ").replace("\n", " ")
        lines.append("\t".join([domain, include_sub, cpath, secure, str(expires), name, value]))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        path.chmod(0o600)  # حاوی توکن نشست است — فقط کاربر فعلی
    except OSError:
        pass
    return path
